/** @type {import('tailwindcss').Config} */
module.exports = {
  mode: 'jit',
  content: ['src/**/*.{ts,tsx}'],
  theme: {
    extend: {
      colors: {
        black: 'hsl(var(--black))',
        white: 'hsl(var(--white))',
        ring: 'hsl(var(--ring))',
        coal: {
          50: 'hsl(var(--coal-50), <alpha-value>)',
          100: 'hsl(var(--coal-100), <alpha-value>)',
          200: 'hsl(var(--coal-200), <alpha-value>)',
          300: 'hsl(var(--coal-300), <alpha-value>)',
          400: 'hsl(var(--coal-400), <alpha-value>)',
          500: 'hsl(var(--coal-500), <alpha-value>)',
          600: 'hsl(var(--coal-600), <alpha-value>)',
          700: 'hsl(var(--coal-700), <alpha-value>)',
          800: 'hsl(var(--coal-800), <alpha-value>)',
          900: 'hsl(var(--coal-900), <alpha-value>)',
          950: 'hsl(var(--coal-950), <alpha-value>)',
        },
        navy: {
          50: 'hsl(var(--navy-50), <alpha-value>)',
          100: 'hsl(var(--navy-100), <alpha-value>)',
          200: 'hsl(var(--navy-200), <alpha-value>)',
          300: 'hsl(var(--navy-300), <alpha-value>)',
          400: 'hsl(var(--navy-400), <alpha-value>)',
          500: 'hsl(var(--navy-500), <alpha-value>)',
          600: 'hsl(var(--navy-600), <alpha-value>)',
          700: 'hsl(var(--navy-700), <alpha-value>)',
          800: 'hsl(var(--navy-800), <alpha-value>)',
          900: 'hsl(var(--navy-900), <alpha-value>)',
          950: 'hsl(var(--navy-950), <alpha-value>)',
        },
        green: {
          50: 'hsl(var(--green-50), <alpha-value>)',
          100: 'hsl(var(--green-100), <alpha-value>)',
          200: 'hsl(var(--green-200), <alpha-value>)',
          300: 'hsl(var(--green-300), <alpha-value>)',
          400: 'hsl(var(--green-400), <alpha-value>)',
          500: 'hsl(var(--green-500), <alpha-value>)',
          600: 'hsl(var(--green-600), <alpha-value>)',
          700: 'hsl(var(--green-700), <alpha-value>)',
          800: 'hsl(var(--green-800), <alpha-value>)',
          900: 'hsl(var(--green-900), <alpha-value>)',
          950: 'hsl(var(--green-950), <alpha-value>)',
        },
        red: {
          50: 'hsl(var(--red-50), <alpha-value>)',
          100: 'hsl(var(--red-100), <alpha-value>)',
          200: 'hsl(var(--red-200), <alpha-value>)',
          300: 'hsl(var(--red-300), <alpha-value>)',
          400: 'hsl(var(--red-400), <alpha-value>)',
          500: 'hsl(var(--red-500), <alpha-value>)',
          600: 'hsl(var(--red-600), <alpha-value>)',
          700: 'hsl(var(--red-700), <alpha-value>)',
          800: 'hsl(var(--red-800), <alpha-value>)',
          900: 'hsl(var(--red-900), <alpha-value>)',
          950: 'hsl(var(--red-950), <alpha-value>)',
        },
        foreground: {
          main: 'hsl(var(--foreground-main))',
          subtle: 'hsl(var(--foreground-subtle))',
          least: 'hsl(var(--foreground-least))',
          alpha: 'hsl(var(--foreground-alpha), 30%)',
          inverted: 'hsl(var(--foreground-inverted))',
        },
        background: {
          main: 'hsl(var(--background-main))',
          subtle: 'hsl(var(--background-subtle))',
          least: 'hsl(var(--background-least))',
          alpha: 'hsl(var(--background-alpha), 10%)',
          max: 'hsl(var(--background-max))',
        },
        accent: {
          main: 'hsl(var(--accent-main))',
          most: 'hsl(var(--accent-most))',
          least: 'hsl(var(--accent-least))',
          alpha: 'hsl(var(--accent-alpha, 20%)',
          back: 'hsl(var(--accent-back))',
        },
        positive: {
          main: 'hsl(var(--positive-main))',
          most: 'hsl(var(--positive-most))',
          least: 'hsl(var(--positive-least))',
          alpha: 'hsl(var(--positive-alpha), 20%)',
          back: 'hsl(var(--positive-back))',
        },
        negative: {
          main: 'hsl(var(--negative-main))',
          most: 'hsl(var(--negative-most))',
          least: 'hsl(var(--negative-least))',
          alpha: 'hsl(var(--negative-alpha), 20%)',
          back: 'hsl(var(--negative-back))',
        },
      },
      borderRadius: {
        lg: `var(--radius)`,
        md: `calc(var(--radius) - 2px)`,
        sm: 'calc(var(--radius) - 4px)',
      },
      keyframes: {
        'accordion-down': {
          from: { height: 0 },
          to: { height: 'var(--radix-accordion-content-height)' },
        },
        'accordion-up': {
          from: { height: 'var(--radix-accordion-content-height)' },
          to: { height: 0 },
        },
      },
      animation: {
        'accordion-down': 'accordion-down 0.2s ease-out',
        'accordion-up': 'accordion-up 0.2s ease-out',
      },
    },
  },
  plugins: [],
};
